
DROP TABLE MEMBER
CASCADE CONSTRAINTS;

DROP SEQUENCE MEMBER_SEQ;

CREATE TABLE MEMBER(
	MEMBER_SEQ NUMBER(8) NOT NULL,
	EMAIL VARCHAR2(100) PRIMARY KEY,
	PASSWORD VARCHAR2(100) NOT NULL,
	ADDRESS VARCHAR2(500),
	PHONENUMBER VARCHAR2(50) NOT NULL,
	USERNAME VARCHAR2(50),
	MEMBER_DATE VARCHAR2(50) NOT NULL,
	AUTH NUMBER(2) NOT NULL	/*회원:0,관리자3 */
);

CREATE SEQUENCE MEMBER_SEQ
START WITH 1
INCREMENT BY 1;

UPDATE MEMBER
SET PASSWORD='admin'
WHERE EMAIL='admin'

INSERT INTO MEMBER
VALUES(MEMBER_SEQ.NEXTVAL, 'admin', 'admin', '', '010-0000-0000', '관리자', SYSDATE, 3)

SELECT * FROM MEMBER